# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Wolicheng.WoMicDriver
PackageVersion: 1.6.0.0
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://wolicheng.com/womic/softwares/womic_driver_setup.exe
  InstallerSha256: 39DCA41DD8823AE0D02472F07827D8EF2E09F01DFD844F73748C66549F491168
ManifestType: installer
ManifestVersion: 1.0.0

